import type { Certificate, Project } from './types';

export const initialProjects: Project[] = [
  {
    id: 'project-1',
    slug: 'tech-wizard-portfolio',
    title: 'Tech Wizard Portfolio',
    description: 'Personal portfolio showcasing projects, certifications, and creative technology work.',
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31',
    tags: ['HTML', 'CSS', 'JavaScript'],
    github: 'https://github.com/',
    demo: 'https://example.com',
    icon: 'fa-code',
    published: true,
    sortOrder: 1,
  },
  {
    id: 'project-2',
    slug: 'ai-support-bot',
    title: 'AI Support Bot',
    description: 'A lightweight chatbot concept for answering common support questions.',
    image: 'https://images.unsplash.com/photo-1531746790731-6c087fecd65a',
    tags: ['Python', 'NLP', 'Automation'],
    github: 'https://github.com/',
    demo: 'https://example.com',
    icon: 'fa-robot',
    published: true,
    sortOrder: 2,
  },
];

export const initialCertificates: Certificate[] = [
  {
    id: 'certificate-1',
    slug: 'python-programming',
    title: 'Python Programming',
    issuer: 'Harvard / edX',
    issuedAt: '2025-01-12',
    issuedAtLabel: 'January 2025',
    description: 'Foundational programming concepts, Python syntax, and problem solving.',
    skills: ['Python', 'Programming', 'Problem Solving'],
    certificateFile: 'Harvard_certificate_for_python-1.png',
    icon: 'fa-certificate',
    published: true,
    sortOrder: 1,
  },
  {
    id: 'certificate-2',
    slug: 'html-and-css',
    title: 'HTML and CSS',
    issuer: 'edX',
    issuedAt: '2025-03-28',
    issuedAtLabel: 'March 2025',
    description: 'Responsive web design fundamentals and clean interface structure.',
    skills: ['HTML', 'CSS', 'Responsive Design'],
    certificateFile: 'HTML AND CSS CERTIFICATE EDX-1.png',
    icon: 'fa-certificate',
    published: true,
    sortOrder: 2,
  },
];
